### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by randompersononinternet69** [Mrbt0907/The-Engender-Mod#1]
**Describe the bug**
The mod seems to fail to build due to it not being able to determine the java version. I did everything I was supposed to do, and it still failed.

**To Reproduce**
1. Open Command Prompt
2. Go to mod source code directory
3. Run gradlew
**Logs and/or Screenshots**
```
17:28:01.388 [ERROR] [org.gradle.BuildExceptionReporter]
17:28:01.431 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:28:01.431 [ERROR] [org.gradle.BuildExceptionReporter]
17:28:01.432 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:28:01.432 [ERROR] [org.gradle.BuildExceptionReporter] Could not determine java version from '19.0.2'.
17:28:01.433 [ERROR] [org.gradle.BuildExceptionReporter]
17:28:01.433 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:28:01.434 [ERROR] [org.gradle.BuildExceptionReporter] java.lang.IllegalArgumentException: Could not determine java version from '19.0.2'.
17:28:01.434 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:68)
17:28:01.434 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.JavaVersion.current(JavaVersion.java:78)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
17:28:01.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
17:28:01.436 [ERROR] [org.gradle.BuildExceptionReporter]        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
17:28:01.437 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
17:28:01.437 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
17:28:01.437 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by Mrbt0907** [comment]
You need to use Java 8 JDK to build with Engender. And if you plan to use the latest version, you won't be able to as it requires a private mod.
